[[redirects]]
    from = "vekt"
    to = "https://modest-edison-d39fe9.netlify.com"
    status = 301
[[redirects]]
    from = "middag"
    to = "https://goofy-bhaskara-518a26.netlify.app"
    status = 301
