[[redirects]]
    from = "jam"
    to = "https://jam-docs-ole-dev.netlify.app"
    status = 200
[[redirects]]
    from = "css/styles.css"
    to = "https://jam-docs-ole-dev.netlify.app/css/styles.css"
    status = 200
    
[[redirects]]
    from = "middag"
    to = "https://middagsmeny.netlify.app"
    status = 301

[[redirects]]
    from = "dash"
    to = "https://dailydash.netlify.app"
    status = 200
[[redirects]]
    from = "assets/*"
    to = "https://dailydash.netlify.app/assets/:splat"
    status = 200

[[redirects]]
    from = "notes/*"
    to = "https://notathage.netlify.app/notes/:splat"
    status = 200

[[redirects]]
    from = "styles/style.css"
    to = "https://notathage.netlify.app/styles/style.css"
    status = 200

[[redirects]]
    from = "riddlr"
    to = "https://riddlr.netlify.app/"
    status = 301
    
[[redirects]]
    from = "nfts/*"
    to = "https://ole-dev-nft.netlify.app/nfts/:splat"
    status = 200    
[[redirects]]
    from = "nft/*"
    to = "https://ole-dev-nft.netlify.app/:splat"
    status = 200
    
[[redirects]]
    from = "nftcss/*"
    to = "https://ole-dev-nft.netlify.app/nftcss/:splat"
    status = 200
    
