[[redirects]]
    from = "jam"
    to = "https://jam-docs-ole-dev.netlify.app"
    status = 200
[[redirects]]
    from = "css/styles.css"
    to = "https://jam-docs-ole-dev.netlify.app/css/styles.css"
    status = 200
    
[[redirects]]
    from = "middag"
    to = "https://middagsmeny.netlify.app"
    status = 301

[[redirects]]
    from = "dash"
    to = "https://dailydash.netlify.app"
    status = 200
[[redirects]]
    from = "assets/*"
    to = "https://dailydash.netlify.app/assets/:splat"
    status = 200

[[redirects]]
    from = "notes/*"
    to = "https://ole-dev-notes.netlify.app/notes/:splat"
    status = 200

[[redirects]]
    from = "styles/style.css"
    to = "https://ole-dev-notes.netlify.app/styles/style.css"
    status = 200

[[redirects]]
    from = "riddlr"
    to = "https://riddlr.netlify.app/"
    status = 301
