[[redirects]]
    from = "jam"
    to = "https://jam-docs-ole-dev.netlify.app"
    status = 200
[[redirects]]
    from = "middag"
    to = "https://goofy-bhaskara-518a26.netlify.app"
    status = 301
